import os
from dotenv import load_dotenv

load_dotenv()

#Project Params
NUMBER_OF_COINS = os.getenv("NUMBER_OF_COINS")

#SERVICES CONFIG INFO

POSTGRES_USER=os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD=os.getenv("POSTGRES_PASSWORD")


POSTGRES_HOST=os.getenv("POSTGRES_HOST")
POSTGRES_PORT=os.getenv("POSTGRES_PORT")
POSTGRES_DATABASE_NAME=os.getenv("POSTGRES_DATABASE_NAME")
POSTGRES_TABLE_META_DATA=os.getenv("POSTGRES_TABLE_META_DATA")
POSTGRES_TABLE_META_DATA_ID=os.getenv("POSTGRES_TABLE_META_DATA_ID")
POSTGRES_TABLE_META_DATA_IS_MONITORED=os.getenv('POSTGRES_TABLE_META_DATA_IS_MONITORED')
POSTGRES_TABLE_META_DATA_NAME=os.getenv('POSTGRES_TABLE_META_DATA_NAME')
POSTGRES_TABLE_META_DATA_SYMBOL=os.getenv('POSTGRES_TABLE_META_DATA_SYMBOL')

CASSANDRA_USER=os.getenv("CASSANDRA_USER")
CASSANDRA_PASSWORD=os.getenv("CASSANDRA_PASSWORD")

CASSANDRA_HOST=os.getenv("CASSANDRA_HOST")
CASSANDRA_PORT=os.getenv("CASSANDRA_PORT")
CASSANDRA_KEYSPACE=os.getenv("CASSANDRA_KEYSPACE")
CASSANDRA_TABLE_CRYPTO_PRICE_DATA=os.getenv("CASSANDRA_TABLE_CRYPTO_PRICE_DATA")
CASSANDRA_TABLE_CRYPTO_PRICE_DATA_ID=os.getenv("CASSANDRA_TABLE_CRYPTO_PRICE_DATA_ID")
CASSANDRA_TABLE_CRYPTO_PRICE_DATA_READ_TS=os.getenv("CASSANDRA_TABLE_CRYPTO_PRICE_DATA_READ_TS")

KAFKA_HOST=os.getenv("KAFKA_HOST")
KAFKA_PORT=os.getenv("KAFKA_OUTSIDE_PORT")
KAFKA_TOPIC_HOURLY_PRICE=os.getenv("KAFKA_TOPIC_HOURLY_PRICE")

TWITTER_API_KEY=os.getenv("TWITTER_API_KEY")
TWITTER_API_KEY_SECRET=os.getenv("TWITTER_API_KEY_SECRET")
TWITTER_ACCESS_TOKEN=os.getenv("TWITTER_ACCESS_TOKEN")
TWITTER_ACCESS_TOKEN_SECRET=os.getenv("TWITTER_ACCESS_TOKEN_SECRET")
TWITTER_BEARER_TOKEN=os.getenv("TWITTER_BEARER_TOKEN")

ELASTIC_HOST=os.getenv("ELASTIC_HOST")
ELASTIC_USERNAME=os.getenv("ELASTIC_USERNAME")
ELASTIC_PASSWORD=os.getenv("ELASTIC_PASSWORD")
ELASTIC_PORT=os.getenv("ELASTIC_PORT")
ELASTIC_REDDIT_INDEX_NAME=os.getenv("ELASTIC_REDDIT_INDEX_NAME")

REDDIT_CLIENT_SECRET=os.getenv("REDDIT_CLIENT_SECRET")
REDDIT_APP_ID=os.getenv("REDDIT_APP_ID")
REDDIT_CLIENT_ID=os.getenv("REDDIT_CLIENT_ID")