import os
from dotenv import load_dotenv

load_dotenv()

#Project Params
NUMBER_OF_COINS = os.getenv("NUMBER_OF_COINS")

#SERVICES CONFIG INFO

POSTGRES_USER=os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD=os.getenv("POSTGRES_PASSWORD")


POSTGRES_HOST=os.getenv("POSTGRES_HOST")
POSTGRES_PORT=os.getenv("POSTGRES_PORT")
POSTGRES_DATABASE_NAME=os.getenv("POSTGRES_DATABASE_NAME")
POSTGRES_TABLE_META_DATA=os.getenv("POSTGRES_TABLE_META_DATA")
POSTGRES_TABLE_META_DATA_ID=os.getenv("POSTGRES_TABLE_META_DATA_ID")


CASSANDRA_USER=os.getenv("CASSANDRA_USER")
CASSANDRA_PASSWORD=os.getenv("CASSANDRA_PASSWORD")


CASSANDRA_HOST=os.getenv("CASSANDRA_HOST")
CASSANDRA_PORT=os.getenv("CASSANDRA_PORT")
CASSANDRA_KEYSPACE=os.getenv("CASSANDRA_KEYSPACE")
CASSANDRA_TABLE_CRYPTO_PRICE_DATA=os.getenv("CASSANDRA_TABLE_CRYPTO_PRICE_DATA")
CASSANDRA_TABLE_CRYPTO_PRICE_DATA_ID=os.getenv("CASSANDRA_TABLE_CRYPTO_PRICE_DATA_ID")
CASSANDRA_TABLE_CRYPTO_PRICE_DATA_READ_TS=os.getenv("CASSANDRA_TABLE_CRYPTO_PRICE_DATA_READ_TS")

KAFKA_HOST=os.getenv("KAFKA_HOST")
KAFKA_PORT=os.getenv("KAFKA_OUTSIDE_PORT")
