
services:
  cassandra:
    image: bitnami/cassandra:4.0
    platform: linux/arm64
    user: root
    container_name: cassandra
    ports:
      - "${CASSANDRA_HOST_PORT_NATIVE}:${CASSANDRA_DOCKER_PORT_NATIVE}" 
      - "${CASSANDRA_HOST_PORT_INTER}:${CASSANDRA_DOCKER_PORT_INTER}" 
    volumes:
      - ${VOLUME_CASSANDRA}:/bitnami
      - ./cql_scripts/:/docker-entrypoint-initdb.d
    environment:
      - CASSANDRA_CLUSTER_NAME=crypto-cluster
      - CASSANDRA_DC=datacenter1
      - cluster.rack=rack1
      - CASSANDRA_SEEDS=cassandra

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ${VOLUME_POSTGRES}:/var/lib/postgresql/data
      - ./sql_scripts/tables.sql:/docker-entrypoint-initdb.d/tables.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}

  zookeeper:
    image: zookeeper:3.7.1
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "${KAFKA_OUTSIDE_PORT}:${KAFKA_OUTSIDE_PORT}"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:${KAFKA_INSIDE_PORT},OUTSIDE://${KAFKA_HOST}:${KAFKA_OUTSIDE_PORT}
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:${KAFKA_INSIDE_PORT},OUTSIDE://0.0.0.0:${KAFKA_OUTSIDE_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
    depends_on:
        - zookeeper

  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=false #disabling https
    ports:
      - "${ELASTIC_PORT}:${ELASTIC_PORT}"  # Expose port 9200 for HTTP communication
    volumes:
        - ${VOLUME_ELASTIC}:/usr/share/elasticsearch/data

volumes:
  cassandra:
  postgres:
  esdata: